databases:
  - name: study_planner_db
    databaseName: study_planner
    user: planner
    plan: free  # Use "starter" for production

services:
  - type: web
    name: study-planner-backend
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: study_planner_db
          property: connectionString
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.6

envVars:
  - key: ADMIN_USER
    value: study_admin  # Or your preferred username
  - key: ADMIN_PASS
    generateValue: true  # Render will generate and secure this
  - key: FLASK_ENV
    value: production